version: '3' # especificamos la version del schema de docker-compose que se utiliza
services:  ## definimos los servicios que se ejecutaran 
  libreria-itz:  # API de libreria ITZ
    build: 
      context: .   # iniciamos la ruta para construir el servicio 
      dockerfile: Dockerfile   # especificamos el archivo del contructor 
    ports:
      - "3001:3000"  # hacemos el mapeo de puertos 
    image: libreria-itz-image:tag  # definos el nombre de la imagen
    depends_on:  
      - mongo  # nombre del servicio de cual depende
    environment:  # definimos las variables de entorno
      - MONGO_URL=mongodb://mongo:27017/libreria_itz_db  # definimos la url de la base de datos
    command: node index  # nos aseguramos de iniciar la aplicacion 
  mongo:  # servicio de base de datos
    image: mongo:6.0  # definimos la imagen a utilizar oficial de mongo db 6.0
    container_name: mongo  # asignamos el nombre del contenedor
    ports:
      - "27017:27017"  # mapeamos el puerto 27017 al contenedos 27017 del host 
    volumes:  # definimos los volumenes
      - mongo-data:/data/db  # monstar un volumen persistente en la ruta dentro del contenedor donde mogno guarda los datos
volumes:  # definimos los volumenes
  mongo-data:  #  volumen mongo-data lo vamos a utulizar para guardar los datos de MONGO DB fuera del contenedor 



    
